### ISSUE TITLE
Limits on contributors subfields

### ISSUE THREAD

**Issue by mgrauer** [dandi/schema#11]
@mvandenburgh asked what are the character size limits on Contributor:

- name
- email
- orcid
- affiliation

**Comment by satra** [comment]
orcid is no longer a key. do make sure to follow the new schema, which has many other fields. 

so there is a more complex identifier that we will be using and since this can be structured or a url it will have different limits.

the rest i would say should follow normal notions 

name: 255
email: 254
affiliation: 255 (and note this is a list of things).

i would be worried if we had to set limits on each key beyond standard json/yaml schema limits. if it is about presentation, can we use css to guide this rather than specific fixed limits. i also suspect we will be creating custom widgets for different pieces of information. 

if it's about editing, i definitely want to see this a bit as the new schema is a lot more complex in terms of information structuring.

**Comment by yarikoptic** [comment]
I will consider this one done (in dandi-cli)
