### ISSUE TITLE
clean up repository

### ISSUE THREAD

**Issue by satra** [dandi/schema#19]
there are a bunch of things in this directory that probably should get cleaned up. also we should publish the schema docs by version in a gh-pages branch. this came up in a conversation and filing for now.

**Comment by yarikoptic** [comment]
I do not know what "things" you had in mind @satra since none was listed explicitly.  From a brief look we seems to be quite "clean". May be "things" got cleaned up?  if you find smth to be removed, go ahead and remove it or reopen and list here.

As for extra features - should better get dedicated issues with more detailed description. Since not acted anyhow in over a year, I will close for now altogether.
